### ISSUE TITLE
Add CI check to prevent merging code with ESLint violations

### ISSUE THREAD

**Issue by mlld-dev** [mlld-lang/mlld#180]
## Context

We've added custom ESLint rules to enforce clean AST patterns, but currently there's no CI enforcement to prevent merging code that violates these rules.

## Problem

Without CI enforcement:
- Violations can be merged to main branch
- Technical debt accumulates
- The linting rules lose their effectiveness

## Proposed Solution

Add GitHub Actions workflow that:
1. Runs ESLint on pull requests
2. Fails the build if there are any violations
3. Provides clear feedback about what needs to be fixed

### Example Workflow

```yaml
name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build grammar (required for linting)
      run: npm run build:grammar
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run AST-specific linting
      run: npm run lint:ast
```

## Benefits

- Prevents new violations from being introduced
- Maintains code quality standards
- Makes custom linting rules actually effective
- Provides immediate feedback to contributors

## Acceptance Criteria

- [ ] GitHub Actions workflow created for linting
- [ ] Workflow runs on all PRs to main
- [ ] Build fails if ESLint reports any errors
- [ ] Clear error messages shown in PR checks
- [ ] Documentation updated to mention CI linting
